name: Update Top 50 Stocks with Metrics

on:
  schedule:
    - cron: '30 12 * * *'  # Runs daily at 6:00 PM IST (12:30 PM UTC)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nsepython nsepy pandas numpy

      - name: Run update script
        run: python update_stocks.py

      - name: Set up git user
        run: |
          git config --global user.email "23f2004586@ds.study.iitm.ac.in"
          git config --global user.name "23f2004586"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update top 50 performing stocks with metrics [skip ci]"
          branch: main
          commit_user_name: "23f2004586"
          commit_user_email: "23f2004586@ds.study.iitm.ac.in"
          token: ${{ secrets.GH_TOKEN }}
